// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5DWsxD5mE4XmLqjI4_zKSvI_-KGbr0dI',
    appId: '1:58529973806:android:d98c1f65b99fc6adf981bf',
    messagingSenderId: '58529973806',
    projectId: 'animal-arch-test',
    storageBucket: 'animal-arch-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEnhqQqakPXn9jTJnhZOo3iPaw8qqXC8A',
    appId: '1:58529973806:ios:5984731505819f04f981bf',
    messagingSenderId: '58529973806',
    projectId: 'animal-arch-test',
    storageBucket: 'animal-arch-test.appspot.com',
    iosClientId: '58529973806-itcjefi7fhht2or6ft6elgejiuvkgagt.apps.googleusercontent.com',
    iosBundleId: 'com.example.animal.test',
  );
}
